export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  MANUFACTURER_ADMIN: 'MANUFACTURER_ADMIN',
  DISTRIBUTOR_ADMIN: 'DISTRIBUTOR_ADMIN',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  DASHBOARD_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  APPROVALS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  MANUFACTURERS_VIEW: [ROLES.SUPER_ADMIN],
  DISTRIBUTORS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN],
  SALESMEN_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  PRODUCTS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  PRODUCT_CATEGORIES_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  SHOPS_VIEW: [ROLES.SUPER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  VISITS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  WORKING_DAYS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  ORDERS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  ORDER_STATUSES_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN],
  INVENTORY_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  BACKORDERS_VIEW: [ROLES.SUPER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  FULFILLMENT_VIEW: [ROLES.SUPER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  NOTIFICATIONS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  ANALYTICS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
  AUDIT_LOGS_VIEW: [ROLES.SUPER_ADMIN],
  SETTINGS_VIEW: [ROLES.SUPER_ADMIN, ROLES.MANUFACTURER_ADMIN, ROLES.DISTRIBUTOR_ADMIN],
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
