export const SOCKET_EVENTS = {
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  BACKORDER_CREATED: 'BACKORDER_CREATED',
  VISIT_STARTED: 'VISIT_STARTED',
  VISIT_ENDED: 'VISIT_ENDED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  SALESMAN_CHECKED_IN: 'SALESMAN_CHECKED_IN',
  SALESMAN_CHECKED_OUT: 'SALESMAN_CHECKED_OUT',
  BACKORDER_ALLOCATED: 'backorder:allocated',
  INVENTORY_UPDATED: 'inventory:updated',
  BACKORDER_RESOLVED: 'backorder:resolved',
  LOCATION_UPDATED: 'LOCATION_UPDATED',
  APPROVAL_STATUS_CHANGED: 'APPROVAL_STATUS_CHANGED',
  NEW_ORDER: 'NEW_ORDER',
  ORDER_EDITED: 'ORDER_EDITED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
} as const;

export type SocketEvent = keyof typeof SOCKET_EVENTS;
