import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCategoryDescription1782005995220 implements MigrationInterface {
    name = 'AddCategoryDescription1782005995220'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_061e6be12ade8887d17160dfe5e"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4edea41c25dc315382611dd4782"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32"`);
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f"`);
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_159a428a7a1279c22e746db2538"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_421761540aa42ee87d60a8869d9"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_shop"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_salesman"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_salesman_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_working_day"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_distributor"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "backorders" ALTER COLUMN "order_item_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geography(Point,4326)`);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_salesman" ON "shop_visits"  ("salesman_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_distributor" ON "shop_visits"  ("distributor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_shop" ON "shop_visits"  ("shop_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_working_day" ON "shop_visits"  ("working_day_id") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_created_at" ON "shop_visits"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_salesman_status" ON "shop_visits"  ("salesman_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_dist_status" ON "shop_visits"  ("distributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_created_at" ON "backorders"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_dist_status" ON "backorders"  ("distributor_id", "status") `);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc" FOREIGN KEY ("salesman_id") REFERENCES "salesmen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_421761540aa42ee87d60a8869d9" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_159a428a7a1279c22e746db2538" FOREIGN KEY ("working_day_id") REFERENCES "working_days"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4edea41c25dc315382611dd4782" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_061e6be12ade8887d17160dfe5e" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f"`);
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_061e6be12ade8887d17160dfe5e"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4edea41c25dc315382611dd4782"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_159a428a7a1279c22e746db2538"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_421761540aa42ee87d60a8869d9"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_salesman_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_working_day"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_shop"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_distributor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_salesman"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "backorders" ALTER COLUMN "order_item_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geography(Point,4326)`);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_distributor" ON "shop_visits" USING btree ("distributor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_working_day" ON "shop_visits" USING btree ("working_day_id") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_dist_status" ON "shop_visits" USING btree ("distributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_created_at" ON "shop_visits" USING btree ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_salesman_status" ON "shop_visits" USING btree ("salesman_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_salesman" ON "shop_visits" USING btree ("salesman_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_shop" ON "shop_visits" USING btree ("shop_id") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_dist_status" ON "backorders" USING btree ("distributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_created_at" ON "backorders" USING btree ("created_at") `);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc" FOREIGN KEY ("salesman_id") REFERENCES "salesmen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_421761540aa42ee87d60a8869d9" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_159a428a7a1279c22e746db2538" FOREIGN KEY ("working_day_id") REFERENCES "working_days"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4edea41c25dc315382611dd4782" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_061e6be12ade8887d17160dfe5e" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
