import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidv4 } from 'uuid';

export class CreateAndSeedStatesAndCities1782006000000 implements MigrationInterface {
    name = 'CreateAndSeedStatesAndCities1782006000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Create states table if not exists
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "states" (
                "id" uuid NOT NULL,
                "name" character varying(150) NOT NULL,
                "created_at" TIMESTAMP NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
                "deleted_at" TIMESTAMP,
                CONSTRAINT "UQ_states_name" UNIQUE ("name"),
                CONSTRAINT "PK_states" PRIMARY KEY ("id")
            )
        `);

        // Create cities table if not exists
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "cities" (
                "id" uuid NOT NULL,
                "name" character varying(150) NOT NULL,
                "state_id" uuid NOT NULL,
                "created_at" TIMESTAMP NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
                "deleted_at" TIMESTAMP,
                CONSTRAINT "PK_cities" PRIMARY KEY ("id"),
                CONSTRAINT "FK_cities_state" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE CASCADE ON UPDATE NO ACTION
            )
        `);

        // Create index for performance if not exists
        await queryRunner.query(`
            CREATE INDEX IF NOT EXISTS "idx_cities_state_id" ON "cities" ("state_id")
        `);

        const data = [
        {
                "state": "Andhra Pradesh",
                "cities": [
                        "Adoni",
                        "Amalapuram",
                        "Anakapalle",
                        "Anantapur",
                        "Bapatla",
                        "Bheemunipatnam",
                        "Bhimavaram",
                        "Bobbili",
                        "Chilakaluripet",
                        "Chirala",
                        "Chittoor",
                        "Dharmavaram",
                        "Eluru",
                        "Gooty",
                        "Gudivada",
                        "Gudur",
                        "Guntakal",
                        "Guntur",
                        "Hindupur",
                        "Jaggaiahpet",
                        "Jammalamadugu",
                        "Kadapa",
                        "Kadiri",
                        "Kakinada",
                        "Kandukur",
                        "Kavali",
                        "Kovvur",
                        "Kurnool",
                        "Macherla",
                        "Machilipatnam",
                        "Madanapalle",
                        "Mandapeta",
                        "Markapur",
                        "Nagari",
                        "Naidupet",
                        "Nandyal",
                        "Narasapuram",
                        "Narasaraopet",
                        "Narsipatnam",
                        "Nellore",
                        "Nidadavole",
                        "Nuzvid",
                        "Ongole",
                        "Palacole",
                        "Palasa Kasibugga",
                        "Parvathipuram",
                        "Pedana",
                        "Peddapuram",
                        "Pithapuram",
                        "Ponnur",
                        "Proddatur",
                        "Punganur",
                        "Puttur",
                        "Rajahmundry",
                        "Rajam",
                        "Rajampet",
                        "Ramachandrapuram",
                        "Rayachoti",
                        "Rayadurg",
                        "Renigunta",
                        "Repalle",
                        "Salur",
                        "Samalkot",
                        "Sattenapalle",
                        "Srikakulam",
                        "Srikalahasti",
                        "Srisailam Project (Right Flank Colony) Township",
                        "Sullurpeta",
                        "Tadepalligudem",
                        "Tadpatri",
                        "Tanuku",
                        "Tenali",
                        "Tirupati",
                        "Tiruvuru",
                        "Tuni",
                        "Uravakonda",
                        "Venkatagiri",
                        "Vijayawada",
                        "Vinukonda",
                        "Visakhapatnam",
                        "Vizianagaram",
                        "Yemmiganur",
                        "Yerraguntla"
                ]
        },
        {
                "state": "Arunachal Pradesh",
                "cities": [
                        "Itanagar",
                        "Naharlagun",
                        "Pasighat",
                        "Tawang"
                ]
        },
        {
                "state": "Assam",
                "cities": [
                        "Barpeta",
                        "Bongaigaon City",
                        "Dhubri",
                        "Dibrugarh",
                        "Diphu",
                        "Dispur",
                        "Goalpara",
                        "Guwahati",
                        "Jorhat",
                        "Karimganj",
                        "Lanka",
                        "Lumding",
                        "Mangaldoi",
                        "Mankachar",
                        "Margherita",
                        "Mariani",
                        "Marigaon",
                        "Nagaon",
                        "Nalbari",
                        "North Lakhimpur",
                        "Rangia",
                        "Sibsagar",
                        "Silapathar",
                        "Silchar",
                        "Tezpur",
                        "Tinsukia"
                ]
        },
        {
                "state": "Bihar",
                "cities": [
                        "Araria",
                        "Arrah",
                        "Arwal",
                        "Asarganj",
                        "Aurangabad",
                        "Bagaha",
                        "Barh",
                        "Begusarai",
                        "Bettiah",
                        "BhabUrban Agglomeration",
                        "Bhagalpur",
                        "Buxar",
                        "Chhapra",
                        "Darbhanga",
                        "Dehri-on-Sone",
                        "Dumraon",
                        "Forbesganj",
                        "Gaya",
                        "Gopalganj",
                        "Hajipur",
                        "Jamalpur",
                        "Jamui",
                        "Jehanabad",
                        "Katihar",
                        "Kishanganj",
                        "Lakhisarai",
                        "Lalganj",
                        "Madhepura",
                        "Madhubani",
                        "Maharajganj",
                        "Mahnar Bazar",
                        "Makhdumpur",
                        "Maner",
                        "Manihari",
                        "Marhaura",
                        "Masaurhi",
                        "Mirganj",
                        "Mokameh",
                        "Motihari",
                        "Motipur",
                        "Munger",
                        "Murliganj",
                        "Muzaffarpur",
                        "Narkatiaganj",
                        "Naugachhia",
                        "Nawada",
                        "Nokha",
                        "Patna",
                        "Piro",
                        "Purnia",
                        "Rafiganj",
                        "Rajgir",
                        "Ramnagar",
                        "Raxaul Bazar",
                        "Revelganj",
                        "Rosera",
                        "Saharsa",
                        "Samastipur",
                        "Sasaram",
                        "Sheikhpura",
                        "Sheohar",
                        "Sherghati",
                        "Silao",
                        "Sitamarhi",
                        "Siwan",
                        "Sonepur",
                        "Sugauli",
                        "Sultanganj",
                        "Supaul",
                        "Warisaliganj"
                ]
        },
        {
                "state": "Chhattisgarh",
                "cities": [
                        "Ambikapur",
                        "Bhatapara",
                        "Bhilai",
                        "Bhilai Nagar",
                        "Bilaspur",
                        "Chirmiri",
                        "Dalli-Rajhara",
                        "Dhamtari",
                        "Durg",
                        "Jagdalpur",
                        "Korba",
                        "Mahasamund",
                        "Manendragarh",
                        "Mungeli",
                        "Naila Janjgir",
                        "Raigarh",
                        "Raipur",
                        "Rajnandgaon",
                        "Sakti",
                        "Tilda Newra"
                ]
        },
        {
                "state": "Goa",
                "cities": [
                        "Mapusa",
                        "Margao",
                        "Marmagao",
                        "Panaji",
                        "Vasco da Gama"
                ]
        },
        {
                "state": "Gujarat",
                "cities": [
                        "Adalaj",
                        "Ahmedabad",
                        "Amreli",
                        "Anand",
                        "Anjar",
                        "Ankleshwar",
                        "Bharuch",
                        "Bhavnagar",
                        "Bhuj",
                        "Chhapra",
                        "Deesa",
                        "Dhoraji",
                        "Gandhinagar",
                        "Godhra",
                        "Jamnagar",
                        "Kadi",
                        "Kapadvanj",
                        "Keshod",
                        "Khambhat",
                        "Lathi",
                        "Limbdi",
                        "Lunawada",
                        "Mahemdabad",
                        "Mahesana",
                        "Mahuva",
                        "Manavadar",
                        "Mandvi",
                        "Mangrol",
                        "Mansa",
                        "Modasa",
                        "Morvi",
                        "Nadiad",
                        "Navsari",
                        "Padra",
                        "Palanpur",
                        "Palitana",
                        "Pardi",
                        "Patan",
                        "Petlad",
                        "Porbandar",
                        "Radhanpur",
                        "Rajkot",
                        "Rajpipla",
                        "Rajula",
                        "Ranavav",
                        "Rapar",
                        "Salaya",
                        "Sanand",
                        "Savarkundla",
                        "Sidhpur",
                        "Sihor",
                        "Songadh",
                        "Surat",
                        "Talaja",
                        "Thangadh",
                        "Tharad",
                        "Umbergaon",
                        "Umreth",
                        "Una",
                        "Unjha",
                        "Upleta",
                        "Vadnagar",
                        "Vadodara",
                        "Valsad",
                        "Vapi",
                        "Veraval",
                        "Vijapur",
                        "Viramgam",
                        "Visnagar",
                        "Vyara",
                        "Wadhwan",
                        "Wankaner"
                ]
        },
        {
                "state": "Haryana",
                "cities": [
                        "Ambala",
                        "Bahadurgarh",
                        "Bhiwani",
                        "Charkhi Dadri",
                        "Faridabad",
                        "Fatehabad",
                        "Gohana",
                        "Gurgaon",
                        "Gurugram",
                        "Hansi",
                        "Hisar",
                        "Jind",
                        "Kaithal",
                        "Karnal",
                        "Ladwa",
                        "Mahendragarh",
                        "Mandi Dabwali",
                        "Narnaul",
                        "Narwana",
                        "Palwal",
                        "Panchkula",
                        "Panipat",
                        "Pehowa",
                        "Pinjore",
                        "Rania",
                        "Ratia",
                        "Rewari",
                        "Rohtak",
                        "Safidon",
                        "Samalkha",
                        "Sarsod",
                        "Shahbad",
                        "Sirsa",
                        "Sohna",
                        "Sonipat",
                        "Taraori",
                        "Thanesar",
                        "Tohana",
                        "Yamunanagar"
                ]
        },
        {
                "state": "Himachal Pradesh",
                "cities": [
                        "Dharamshala",
                        "Kullu",
                        "Mandi",
                        "Nahan",
                        "Palampur",
                        "Shimla",
                        "Solan",
                        "Sundarnagar"
                ]
        },
        {
                "state": "Jharkhand",
                "cities": [
                        "Adityapur",
                        "Bokaro Steel City",
                        "Chaibasa",
                        "Chatra",
                        "Chirkunda",
                        "Deoghar",
                        "Dhanbad",
                        "Dumka",
                        "Giridih",
                        "Gumia",
                        "Hazaribag",
                        "Jamshedpur",
                        "Jhumri Tilaiya",
                        "Lohardaga",
                        "Madhupur",
                        "Medininagar (Daltonganj)",
                        "Mihijam",
                        "Musabani",
                        "Pakaur",
                        "Patratu",
                        "Phusro",
                        "Ramgarh",
                        "Ranchi",
                        "Sahibganj",
                        "Saunda",
                        "Simdega",
                        "Tenu dam-cum-Kathhara"
                ]
        },
        {
                "state": "Karnataka",
                "cities": [
                        "Adyar",
                        "Afzalpur",
                        "Arsikere",
                        "Athni",
                        "Ballari",
                        "Belagavi",
                        "Bengaluru",
                        "Chikkamagaluru",
                        "Davanagere",
                        "Gokak",
                        "Hubballi-Dharwad",
                        "Hubli-Dharwad",
                        "Karwar",
                        "Kolar",
                        "Lakshmeshwar",
                        "Lingsugur",
                        "Maddur",
                        "Madhugiri",
                        "Madikeri",
                        "Magadi",
                        "Mahalingapura",
                        "Malavalli",
                        "Malur",
                        "Mandya",
                        "Mangaluru",
                        "Manvi",
                        "Mudabidri",
                        "Mudalagi",
                        "Muddebihal",
                        "Mudhol",
                        "Mulbagal",
                        "Mundargi",
                        "Mysore",
                        "Mysuru",
                        "Nanjangud",
                        "Nargund",
                        "Navalgund",
                        "Nelamangala",
                        "Pavagada",
                        "Piriyapatna",
                        "Puttur",
                        "Raayachuru",
                        "Rabkavi Banhatti",
                        "Ramanagaram",
                        "Ramdurg",
                        "Ranebennuru",
                        "Ranibennur",
                        "Robertson Pet",
                        "Ron",
                        "Sadalagi",
                        "Sagara",
                        "Sakaleshapura",
                        "Sanduru",
                        "Sankeshwara",
                        "Saundatti-Yellamma",
                        "Savanur",
                        "Sedam",
                        "Shahabad",
                        "Shahpur",
                        "Shiggaon",
                        "Shikaripur",
                        "Shivamogga",
                        "Shrirangapattana",
                        "Sidlaghatta",
                        "Sindagi",
                        "Sindhagi",
                        "Sindhnur",
                        "Sira",
                        "Sirsi",
                        "Siruguppa",
                        "Srinivaspur",
                        "Surapura",
                        "Talikota",
                        "Tarikere",
                        "Tekkalakote",
                        "Terdal",
                        "Tiptur",
                        "Tumkur",
                        "Udupi",
                        "Vijayapura",
                        "Wadi",
                        "Yadgir"
                ]
        },
        {
                "state": "Kerala",
                "cities": [
                        "Adoor",
                        "Alappuzha",
                        "Attingal",
                        "Chalakudy",
                        "Changanassery",
                        "Cherthala",
                        "Chittur-Thathamangalam",
                        "Guruvayoor",
                        "Kanhangad",
                        "Kannur",
                        "Kasaragod",
                        "Kayamkulam",
                        "Kochi",
                        "Kodungallur",
                        "Kollam",
                        "Kottayam",
                        "Koyilandy",
                        "Kozhikode",
                        "Kunnamkulam",
                        "Malappuram",
                        "Mattannur",
                        "Mavelikkara",
                        "Mavoor",
                        "Muvattupuzha",
                        "Nedumangad",
                        "Neyyattinkara",
                        "Nilambur",
                        "Ottappalam",
                        "Palai",
                        "Palakkad",
                        "Panamattom",
                        "Panniyannur",
                        "Pappinisseri",
                        "Paravoor",
                        "Pathanamthitta",
                        "Peringathur",
                        "Perinthalmanna",
                        "Perumbavoor",
                        "Ponnani",
                        "Punalur",
                        "Puthuppally",
                        "Shoranur",
                        "Taliparamba",
                        "Thiruvalla",
                        "Thiruvananthapuram",
                        "Thodupuzha",
                        "Thrissur",
                        "Tirur",
                        "Vaikom",
                        "Varkala",
                        "Vatakara"
                ]
        },
        {
                "state": "Madhya Pradesh",
                "cities": [
                        "Alirajpur",
                        "Ashok Nagar",
                        "Balaghat",
                        "Bhopal",
                        "Ganjbasoda",
                        "Gwalior",
                        "Indore",
                        "Itarsi",
                        "Jabalpur",
                        "Lahar",
                        "Maharajpur",
                        "Mahidpur",
                        "Maihar",
                        "Malaj Khand",
                        "Manasa",
                        "Manawar",
                        "Mandideep",
                        "Mandla",
                        "Mandsaur",
                        "Mauganj",
                        "Mhow Cantonment",
                        "Mhowgaon",
                        "Morena",
                        "Multai",
                        "Mundi",
                        "Murwara (Katni)",
                        "Nagda",
                        "Nainpur",
                        "Narsinghgarh",
                        "Neemuch",
                        "Nepanagar",
                        "Niwari",
                        "Nowgong",
                        "Nowrozabad (Khodargama)",
                        "Pachore",
                        "Pali",
                        "Panagar",
                        "Pandhurna",
                        "Panna",
                        "Pasan",
                        "Pipariya",
                        "Pithampur",
                        "Porsa",
                        "Prithvipur",
                        "Raghogarh-Vijaypur",
                        "Rahatgarh",
                        "Raisen",
                        "Rajgarh",
                        "Ratlam",
                        "Rau",
                        "Rehli",
                        "Rewa",
                        "Sabalgarh",
                        "Sagar",
                        "Sanawad",
                        "Sarangpur",
                        "Sarni",
                        "Satna",
                        "Sausar",
                        "Sehore",
                        "Sendhwa",
                        "Seoni",
                        "Seoni-Malwa",
                        "Shahdol",
                        "Shajapur",
                        "Shamgarh",
                        "Sheopur",
                        "Shivpuri",
                        "Shujalpur",
                        "Sidhi",
                        "Sihora",
                        "Singrauli",
                        "Sironj",
                        "Sohagpur",
                        "Tarana",
                        "Tikamgarh",
                        "Ujjain",
                        "Umaria",
                        "Vidisha",
                        "Vijaypur",
                        "Wara Seoni"
                ]
        },
        {
                "state": "Maharashtra",
                "cities": [
                        "Achalpur",
                        "Ahmednagar",
                        "Akola",
                        "Akot",
                        "Amalner",
                        "Ambejogai",
                        "Amravati",
                        "Anjangaon",
                        "Arvi",
                        "Aurangabad",
                        "Bhiwandi",
                        "Dhule",
                        "Ichalkaranji",
                        "Kalyan-Dombivali",
                        "Karjat",
                        "Latur",
                        "Loha",
                        "Lonar",
                        "Lonavla",
                        "Mahad",
                        "Malegaon",
                        "Malkapur",
                        "Mangalvedhe",
                        "Mangrulpir",
                        "Manjlegaon",
                        "Manmad",
                        "Manwath",
                        "Mehkar",
                        "Mhaswad",
                        "Mira-Bhayandar",
                        "Morshi",
                        "Mukhed",
                        "Mul",
                        "Mumbai",
                        "Murtijapur",
                        "Nagpur",
                        "Nanded-Waghala",
                        "Nandgaon",
                        "Nandura",
                        "Nandurbar",
                        "Narkhed",
                        "Nashik",
                        "Nawapur",
                        "Nilanga",
                        "Osmanabad",
                        "Ozar",
                        "Pachora",
                        "Paithan",
                        "Palghar",
                        "Pandharkaoda",
                        "Pandharpur",
                        "Panvel",
                        "Parbhani",
                        "Parli",
                        "Partur",
                        "Pathardi",
                        "Pathri",
                        "Patur",
                        "Pauni",
                        "Pen",
                        "Phaltan",
                        "Pulgaon",
                        "Pune",
                        "Purna",
                        "Pusad",
                        "Rahuri",
                        "Rajura",
                        "Ramtek",
                        "Ratnagiri",
                        "Raver",
                        "Risod",
                        "Sailu",
                        "Sangamner",
                        "Sangli",
                        "Sangole",
                        "Sasvad",
                        "Satana",
                        "Satara",
                        "Savner",
                        "Sawantwadi",
                        "Shahade",
                        "Shegaon",
                        "Shendurjana",
                        "Shirdi",
                        "Shirpur-Warwade",
                        "Shirur",
                        "Shrigonda",
                        "Shrirampur",
                        "Sillod",
                        "Sinnar",
                        "Solapur",
                        "Soyagaon",
                        "Talegaon Dabhade",
                        "Talode",
                        "Tasgaon",
                        "Thane",
                        "Tirora",
                        "Tuljapur",
                        "Tumsar",
                        "Uchgaon",
                        "Udgir",
                        "Umarga",
                        "Umarkhed",
                        "Umred",
                        "Uran",
                        "Uran Islampur",
                        "Vadgaon Kasba",
                        "Vaijapur",
                        "Vasai-Virar",
                        "Vita",
                        "Wadgaon Road",
                        "Wai",
                        "Wani",
                        "Wardha",
                        "Warora",
                        "Warud",
                        "Washim",
                        "Yavatmal",
                        "Yawal",
                        "Yevla"
                ]
        },
        {
                "state": "Manipur",
                "cities": [
                        "Churachandpur",
                        "Imphal",
                        "Lilong",
                        "Mayang Imphal",
                        "Thoubal"
                ]
        },
        {
                "state": "Meghalaya",
                "cities": [
                        "Nongpoh",
                        "Nongstoin",
                        "Shillong",
                        "Tura"
                ]
        },
        {
                "state": "Mizoram",
                "cities": [
                        "Aizawl",
                        "Champhai",
                        "Lunglei",
                        "Saiha"
                ]
        },
        {
                "state": "Nagaland",
                "cities": [
                        "Dimapur",
                        "Kohima",
                        "Mokokchung",
                        "Tuensang",
                        "Wokha",
                        "Zunheboto"
                ]
        },
        {
                "state": "Odisha",
                "cities": [
                        "Balangir",
                        "Baleshwar Town",
                        "Barbil",
                        "Bargarh",
                        "Baripada Town",
                        "Berhampur",
                        "Bhadrak",
                        "Bhawanipatna",
                        "Bhubaneswar",
                        "Brahmapur",
                        "Byasanagar",
                        "Cuttack",
                        "Dhenkanal",
                        "Jatani",
                        "Jharsuguda",
                        "Kendrapara",
                        "Kendujhar",
                        "Malkangiri",
                        "Nabarangapur",
                        "Paradip",
                        "Parlakhemundi",
                        "Pattamundai",
                        "Phulabani",
                        "Puri",
                        "Rairangpur",
                        "Rajagangapur",
                        "Raurkela",
                        "Rayagada",
                        "Rourkela",
                        "Sambalpur",
                        "Soro",
                        "Sunabeda",
                        "Sundargarh",
                        "Talcher",
                        "Tarbha",
                        "Titlagarh"
                ]
        },
        {
                "state": "Punjab",
                "cities": [
                        "Amritsar",
                        "Barnala",
                        "Batala",
                        "Bathinda",
                        "Dhuri",
                        "Faridkot",
                        "Fazilka",
                        "Firozpur",
                        "Firozpur Cantt.",
                        "Gobindgarh",
                        "Gurdaspur",
                        "Hoshiarpur",
                        "Jagraon",
                        "Jalandhar",
                        "Jalandhar Cantt.",
                        "Kapurthala",
                        "Khanna",
                        "Kharar",
                        "Kot Kapura",
                        "Longowal",
                        "Ludhiana",
                        "Malerkotla",
                        "Malout",
                        "Mansa",
                        "Moga",
                        "Mohali",
                        "Morinda, India",
                        "Mukerian",
                        "Muktsar",
                        "Nabha",
                        "Nakodar",
                        "Nangal",
                        "Nawanshahr",
                        "Pathankot",
                        "Patiala",
                        "Patti",
                        "Pattran",
                        "Phagwara",
                        "Phillaur",
                        "Qadian",
                        "Raikot",
                        "Rajpura",
                        "Rampura Phul",
                        "Rupnagar",
                        "Samana",
                        "Sangrur",
                        "Sirhind Fatehgarh Sahib",
                        "Sujanpur",
                        "Sunam",
                        "Talwara",
                        "Tarn Taran",
                        "Urmar Tanda",
                        "Zira",
                        "Zirakpur"
                ]
        },
        {
                "state": "Rajasthan",
                "cities": [
                        "Ajmer",
                        "Alwar",
                        "Barmer",
                        "Bharatpur",
                        "Bhilwara",
                        "Bikaner",
                        "Jaipur",
                        "Jodhpur",
                        "Kota",
                        "Lachhmangarh",
                        "Ladnu",
                        "Lakheri",
                        "Lalsot",
                        "Losal",
                        "Makrana",
                        "Malpura",
                        "Mandalgarh",
                        "Mandawa",
                        "Mangrol",
                        "Merta City",
                        "Mount Abu",
                        "Nadbai",
                        "Nagar",
                        "Nagaur",
                        "Nasirabad",
                        "Nathdwara",
                        "Neem-Ka-Thana",
                        "Nimbahera",
                        "Nohar",
                        "Nokha",
                        "Pali",
                        "Phalodi",
                        "Phulera",
                        "Pilani",
                        "Pilibanga",
                        "Pindwara",
                        "Pipar City",
                        "Prantij",
                        "Pratapgarh",
                        "Raisinghnagar",
                        "Rajakhera",
                        "Rajaldesar",
                        "Rajgarh (Alwar)",
                        "Rajgarh (Churu)",
                        "Rajsamand",
                        "Ramganj Mandi",
                        "Ramngarh",
                        "Ratangarh",
                        "Rawatbhata",
                        "Rawatsar",
                        "Reengus",
                        "Sadri",
                        "Sadulpur",
                        "Sadulshahar",
                        "Sagwara",
                        "Sambhar",
                        "Sanchore",
                        "Sangaria",
                        "Sardarshahar",
                        "Sawai Madhopur",
                        "Shahpura",
                        "Sheoganj",
                        "Sikar",
                        "Sirohi",
                        "Sojat",
                        "Sri Madhopur",
                        "Sujangarh",
                        "Sumerpur",
                        "Suratgarh",
                        "Takhatgarh",
                        "Taranagar",
                        "Todabhim",
                        "Todaraisingh",
                        "Tonk",
                        "Udaipur",
                        "Udaipurwati",
                        "Vijainagar, Ajmer"
                ]
        },
        {
                "state": "Sikkim",
                "cities": [
                        "Gangtok",
                        "Geyzing",
                        "Namchi"
                ]
        },
        {
                "state": "Tamil Nadu",
                "cities": [
                        "Arakkonam",
                        "Aruppukkottai",
                        "Chennai",
                        "Coimbatore",
                        "Erode",
                        "Gobichettipalayam",
                        "Kancheepuram",
                        "Karur",
                        "Lalgudi",
                        "Madurai",
                        "Manachanallur",
                        "Nagapattinam",
                        "Nagercoil",
                        "Namagiripettai",
                        "Namakkal",
                        "Nandivaram-Guduvancheri",
                        "Nanjikottai",
                        "Natham",
                        "Nellikuppam",
                        "Neyveli (TS)",
                        "O' Valley",
                        "Oddanchatram",
                        "P.N.Patti",
                        "Pacode",
                        "Padmanabhapuram",
                        "Palani",
                        "Palladam",
                        "Pallapatti",
                        "Pallikonda",
                        "Panagudi",
                        "Panruti",
                        "Paramakudi",
                        "Parangipettai",
                        "Pattukkottai",
                        "Perambalur",
                        "Peravurani",
                        "Periyakulam",
                        "Periyasemur",
                        "Pernampattu",
                        "Pollachi",
                        "Polur",
                        "Ponneri",
                        "Pudukkottai",
                        "Pudupattinam",
                        "Puliyankudi",
                        "Punjaipugalur",
                        "Rajapalayam",
                        "Ramanathapuram",
                        "Rameshwaram",
                        "Ranipet",
                        "Rasipuram",
                        "Salem",
                        "Sankarankovil",
                        "Sankari",
                        "Sathyamangalam",
                        "Sattur",
                        "Shenkottai",
                        "Sholavandan",
                        "Sholingur",
                        "Sirkali",
                        "Sivaganga",
                        "Sivagiri",
                        "Sivakasi",
                        "Srivilliputhur",
                        "Surandai",
                        "Suriyampalayam",
                        "Tenkasi",
                        "Thammampatti",
                        "Thanjavur",
                        "Tharamangalam",
                        "Tharangambadi",
                        "Theni Allinagaram",
                        "Thirumangalam",
                        "Thirupuvanam",
                        "Thiruthuraipoondi",
                        "Thiruvallur",
                        "Thiruvarur",
                        "Thuraiyur",
                        "Tindivanam",
                        "Tiruchendur",
                        "Tiruchengode",
                        "Tiruchirappalli",
                        "Tirukalukundram",
                        "Tirukkoyilur",
                        "Tirunelveli",
                        "Tirupathur",
                        "Tiruppur",
                        "Tiruttani",
                        "Tiruvannamalai",
                        "Tiruvethipuram",
                        "Tittakudi",
                        "Udhagamandalam",
                        "Udumalaipettai",
                        "Unnamalaikadai",
                        "Usilampatti",
                        "Uthamapalayam",
                        "Uthiramerur",
                        "Vadakkuvalliyur",
                        "Vadalur",
                        "Vadipatti",
                        "Valparai",
                        "Vandavasi",
                        "Vaniyambadi",
                        "Vedaranyam",
                        "Vellakoil",
                        "Vellore",
                        "Vikramasingapuram",
                        "Viluppuram",
                        "Virudhachalam",
                        "Virudhunagar",
                        "Viswanatham"
                ]
        },
        {
                "state": "Telangana",
                "cities": [
                        "Adilabad",
                        "Bellampalle",
                        "Bhadrachalam",
                        "Bhainsa",
                        "Bhongir",
                        "Bodhan",
                        "Farooqnagar",
                        "Gadwal",
                        "Hyderabad",
                        "Jagtial",
                        "Jangaon",
                        "Kagaznagar",
                        "Kamareddy",
                        "Karimnagar",
                        "Khammam",
                        "Koratla",
                        "Kothagudem",
                        "Kyathampalle",
                        "Mahbubnagar",
                        "Mancherial",
                        "Mandamarri",
                        "Manuguru",
                        "Medak",
                        "Miryalaguda",
                        "Nagarkurnool",
                        "Narayanpet",
                        "Nirmal",
                        "Nizamabad",
                        "Palwancha",
                        "Ramagundam",
                        "Sadasivpet",
                        "Sangareddy",
                        "Siddipet",
                        "Sircilla",
                        "Suryapet",
                        "Tandur",
                        "Vikarabad",
                        "Wanaparthy",
                        "Warangal",
                        "Yellandu"
                ]
        },
        {
                "state": "Tripura",
                "cities": [
                        "Agartala",
                        "Belonia",
                        "Dharmanagar",
                        "Kailasahar",
                        "Khowai",
                        "Pratapgarh",
                        "Udaipur"
                ]
        },
        {
                "state": "Uttar Pradesh",
                "cities": [
                        "Achhnera",
                        "Agra",
                        "Aligarh",
                        "Allahabad",
                        "Amroha",
                        "Azamgarh",
                        "Bahraich",
                        "Chandausi",
                        "Etawah",
                        "Fatehpur Sikri",
                        "Firozabad",
                        "Ghaziabad",
                        "Hapur",
                        "Hardoi",
                        "Jhansi",
                        "Kalpi",
                        "Kanpur",
                        "Khair",
                        "Laharpur",
                        "Lakhimpur",
                        "Lal Gopalganj Nindaura",
                        "Lalganj",
                        "Lalitpur",
                        "Lar",
                        "Loni",
                        "Lucknow",
                        "Mathura",
                        "Meerut",
                        "Mirzapur",
                        "Modinagar",
                        "Moradabad",
                        "Nagina",
                        "Najibabad",
                        "Nakur",
                        "Nanpara",
                        "Naraura",
                        "Naugawan Sadat",
                        "Nautanwa",
                        "Nawabganj",
                        "Nehtaur",
                        "Niwai",
                        "Noida",
                        "Noorpur",
                        "Obra",
                        "Orai",
                        "Padrauna",
                        "Palia Kalan",
                        "Parasi",
                        "Phulpur",
                        "Pihani",
                        "Pilibhit",
                        "Pilkhuwa",
                        "Powayan",
                        "Pukhrayan",
                        "Puranpur",
                        "PurqUrban Agglomerationzi",
                        "Purwa",
                        "Rae Bareli",
                        "Rampur",
                        "Rampur Maniharan",
                        "Rasra",
                        "Rath",
                        "Renukoot",
                        "Reoti",
                        "Robertsganj",
                        "Rudauli",
                        "Rudrapur",
                        "SUrban Agglomerationr",
                        "Sadabad",
                        "Safipur",
                        "Saharanpur",
                        "Sahaspur",
                        "Sahaswan",
                        "Sahawar",
                        "Sahjanwa",
                        "Saidpur",
                        "Sambhal",
                        "Samdhan",
                        "Samthar",
                        "Sandi",
                        "Sandila",
                        "Sardhana",
                        "Seohara",
                        "Shahabad, Hardoi",
                        "Shahabad, Rampur",
                        "Shahganj",
                        "Shahjahanpur",
                        "Shamli",
                        "Shamsabad, Agra",
                        "Shamsabad, Farrukhabad",
                        "Sherkot",
                        "Shikarpur, Bulandshahr",
                        "Shikohabad",
                        "Shishgarh",
                        "Siana",
                        "Sikanderpur",
                        "Sikandra Rao",
                        "Sikandrabad",
                        "Sirsaganj",
                        "Sirsi",
                        "Sitapur",
                        "Soron",
                        "Sultanpur",
                        "Sumerpur",
                        "Tanda",
                        "Thakurdwara",
                        "Thana Bhawan",
                        "Tilhar",
                        "Tirwaganj",
                        "Tulsipur",
                        "Tundla",
                        "Ujhani",
                        "Unnao",
                        "Utraula",
                        "Varanasi",
                        "Vrindavan",
                        "Warhapur",
                        "Zaidpur",
                        "Zamania"
                ]
        },
        {
                "state": "Uttarakhand",
                "cities": [
                        "Bageshwar",
                        "Dehradun",
                        "Haldwani",
                        "Haldwani-cum-Kathgodam",
                        "Hardwar",
                        "Haridwar",
                        "Kashipur",
                        "Manglaur",
                        "Mussoorie",
                        "Nagla",
                        "Nainital",
                        "Pauri",
                        "Pithoragarh",
                        "Ramnagar",
                        "Rishikesh",
                        "Roorkee",
                        "Rudrapur",
                        "Sitarganj",
                        "Srinagar",
                        "Tehri"
                ]
        },
        {
                "state": "West Bengal",
                "cities": [
                        "Adra",
                        "AlipurdUrban Agglomerationr",
                        "Arambagh",
                        "Asansol",
                        "Baharampur",
                        "Balurghat",
                        "Bankura",
                        "Darjiling",
                        "English Bazar",
                        "Gangarampur",
                        "Habra",
                        "Howrah",
                        "Hugli-Chinsurah",
                        "Jalpaiguri",
                        "Jhargram",
                        "Kalimpong",
                        "Kharagpur",
                        "Kolkata",
                        "Mainaguri",
                        "Malda",
                        "Mathabhanga",
                        "Medinipur",
                        "Memari",
                        "Monoharpur",
                        "Murshidabad",
                        "Nabadwip",
                        "Naihati",
                        "Panchla",
                        "PandUrban Agglomeration",
                        "Paschim Punropara",
                        "Purulia",
                        "Raghunathganj",
                        "Raghunathpur",
                        "Raiganj",
                        "Rampurhat",
                        "Ranaghat",
                        "Sainthia",
                        "Santipur",
                        "Siliguri",
                        "Sonamukhi",
                        "Srirampore",
                        "Suri",
                        "Taki",
                        "Tamluk",
                        "Tarakeswar"
                ]
        },
        {
                "state": "Andaman and Nicobar Islands",
                "cities": [
                        "Bambooflat",
                        "Garacharma",
                        "Port Blair"
                ]
        },
        {
                "state": "Chandigarh",
                "cities": [
                        "Chandigarh"
                ]
        },
        {
                "state": "Dadra and Nagar Haveli and Daman and Diu",
                "cities": [
                        "Daman",
                        "Diu",
                        "Silvassa"
                ]
        },
        {
                "state": "Delhi",
                "cities": [
                        "Delhi",
                        "Dwarka",
                        "New Delhi",
                        "Rohini"
                ]
        },
        {
                "state": "Jammu and Kashmir",
                "cities": [
                        "Anantnag",
                        "Baramula",
                        "Baramulla",
                        "Jammu",
                        "KathUrban Agglomeration",
                        "Punch",
                        "Rajauri",
                        "Sopore",
                        "Srinagar",
                        "Udhampur"
                ]
        },
        {
                "state": "Ladakh",
                "cities": [
                        "Kargil",
                        "Leh"
                ]
        },
        {
                "state": "Lakshadweep",
                "cities": [
                        "Agatti",
                        "Kavaratti",
                        "Minicoy"
                ]
        },
        {
                "state": "Puducherry",
                "cities": [
                        "Karaikal",
                        "Mahe",
                        "Pondicherry",
                        "Puducherry",
                        "Yanam"
                ]
        }
];

        for (const item of data) {
            // Check if state is already seeded
            const existingState = await queryRunner.query(
                `SELECT id FROM "states" WHERE name = $1`,
                [item.state]
            );

            let stateId: string;
            if (existingState.length > 0) {
                stateId = existingState[0].id;
            } else {
                stateId = uuidv4();
                await queryRunner.query(
                    `INSERT INTO "states" (id, name) VALUES ($1, $2)`,
                    [stateId, item.state]
                );
            }

            for (const cityName of item.cities) {
                // Check if city is already seeded for this state
                const existingCity = await queryRunner.query(
                    `SELECT id FROM "cities" WHERE name = $1 AND state_id = $2`,
                    [cityName, stateId]
                );

                if (existingCity.length === 0) {
                    const cityId = uuidv4();
                    await queryRunner.query(
                        `INSERT INTO "cities" (id, name, state_id) VALUES ($1, $2, $3)`,
                        [cityId, cityName, stateId]
                    );
                }
            }
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."idx_cities_state_id"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "cities"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "states"`);
    }
}
