import { MigrationInterface, QueryRunner } from "typeorm";

export class VerificationSchemaAudit1781878590828 implements MigrationInterface {
    name = 'VerificationSchemaAudit1781878590828'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_421761540aa42ee87d60a8869d9"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_159a428a7a1279c22e746db2538"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_shop"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_salesman"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_working_day"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_distributor"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "backorders" ALTER COLUMN "order_item_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geography(Point,4326)`);
        await queryRunner.query(`CREATE INDEX "idx_approvals_created_at" ON "approval_requests"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_approvals_mfr_status" ON "approval_requests"  ("manufacturer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_approvals_dist_status" ON "approval_requests"  ("distributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_inventory_dist_prod" ON "distributor_inventory"  ("distributor_id", "product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_location_logs_location" ON "location_logs" USING gist ("location") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_created_at" ON "notifications"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_read" ON "notifications"  ("recipient_user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "idx_salesmen_created_at" ON "salesmen"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_salesmen_dist_status" ON "salesmen"  ("distributor_id", "approval_status") `);
        await queryRunner.query(`CREATE INDEX "idx_shops_created_at" ON "shops"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_shops_dist_status" ON "shops"  ("distributor_id", "verification_status") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_salesman" ON "shop_visits"  ("salesman_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_distributor" ON "shop_visits"  ("distributor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_shop" ON "shop_visits"  ("shop_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_working_day" ON "shop_visits"  ("working_day_id") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_created_at" ON "shop_visits"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_salesman_status" ON "shop_visits"  ("salesman_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_visits_dist_status" ON "shop_visits"  ("distributor_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_orders_idempotency_key" ON "orders"  ("idempotency_key") WHERE idempotency_key IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_orders_created_at" ON "orders"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_dist_status" ON "orders"  ("distributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_salesman_status" ON "orders"  ("salesman_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_shop_status" ON "orders"  ("shop_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_products_created_at" ON "products"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_products_mfr_cat" ON "products"  ("manufacturer_id", "category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_created_at" ON "backorders"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_backorders_dist_status" ON "backorders"  ("distributor_id", "status") `);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc" FOREIGN KEY ("salesman_id") REFERENCES "salesmen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_421761540aa42ee87d60a8869d9" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_159a428a7a1279c22e746db2538" FOREIGN KEY ("working_day_id") REFERENCES "working_days"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_74df0e55b9805db3a83046d5801" FOREIGN KEY ("visit_id") REFERENCES "shop_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_33f20db82908f7685a5c0c58ac6" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_76a57c1665cefc6a2e72f10bee4" FOREIGN KEY ("salesman_id") REFERENCES "salesmen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_21e5337633015419db62cff07d2" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_411024644e2b4d4c13c877fb5e5" FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_db249db755b246770b9ad346c54" FOREIGN KEY ("cancelled_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_5f151d414daab0290f65b517ed4" FOREIGN KEY ("parent_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_5bc36ce05cc397317480efb18f6" FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_a307e60ae848183d43df6809dfb" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_d4131ec6fde82732ee2f3a777cd" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_061e6be12ade8887d17160dfe5e" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "backorders" ADD CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4edea41c25dc315382611dd4782" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" ADD CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032" FOREIGN KEY ("performed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_revisions" ADD CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_965678b54f0a0361ca72c541b20" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" ADD CONSTRAINT "FK_7308b402704ea5e0b18f6e12bf9" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" ADD CONSTRAINT "FK_4ebdee9e9518cb1f460784b56b9" FOREIGN KEY ("matched_shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" ADD CONSTRAINT "FK_db5f4725544eb8d003712a5bbcb" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" DROP CONSTRAINT "FK_db5f4725544eb8d003712a5bbcb"`);
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" DROP CONSTRAINT "FK_4ebdee9e9518cb1f460784b56b9"`);
        await queryRunner.query(`ALTER TABLE "shop_duplicate_logs" DROP CONSTRAINT "FK_7308b402704ea5e0b18f6e12bf9"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_965678b54f0a0361ca72c541b20"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_889f874c2a5c7566f46e36f9f1f"`);
        await queryRunner.query(`ALTER TABLE "order_revisions" DROP CONSTRAINT "FK_e044f9614dfa97c0524cfaf612c"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4b2f3dfc302bb62cf6848c2f032"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e3cecd2e1e1227d1b26d26b2a32"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_e2116b91db3f461e7ad5fd4cd3c"`);
        await queryRunner.query(`ALTER TABLE "fulfillment_logs" DROP CONSTRAINT "FK_4edea41c25dc315382611dd4782"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_9b00ab9bf576d2dc3383835b3bf"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_42fbbfc3f4a7a4c0a43ee15c29a"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_a0c8832f975e0ad2b2c35234be9"`);
        await queryRunner.query(`ALTER TABLE "backorders" DROP CONSTRAINT "FK_061e6be12ade8887d17160dfe5e"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_d4131ec6fde82732ee2f3a777cd"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_a307e60ae848183d43df6809dfb"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_5bc36ce05cc397317480efb18f6"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_5f151d414daab0290f65b517ed4"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_db249db755b246770b9ad346c54"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_411024644e2b4d4c13c877fb5e5"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_21e5337633015419db62cff07d2"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_76a57c1665cefc6a2e72f10bee4"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_33f20db82908f7685a5c0c58ac6"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_74df0e55b9805db3a83046d5801"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_159a428a7a1279c22e746db2538"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_421761540aa42ee87d60a8869d9"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_backorders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_mfr_cat"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_shop_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_salesman_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_idempotency_key"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_salesman_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_visits_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_working_day"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_shop"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_distributor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_visits_salesman"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shops_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shops_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_salesmen_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_salesmen_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_location_logs_location"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_dist_prod"`);
        await queryRunner.query(`DROP INDEX "public"."idx_approvals_dist_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_approvals_mfr_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_approvals_created_at"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geometry(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "backorders" ALTER COLUMN "order_item_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "end_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "end_location" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "shop_visits" DROP COLUMN "start_location"`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD "start_location" geography(Point,4326)`);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_distributor" ON "shop_visits" USING btree ("distributor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_working_day" ON "shop_visits" USING btree ("working_day_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_salesman" ON "shop_visits" USING btree ("salesman_id") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_visits_shop" ON "shop_visits" USING btree ("shop_id") `);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_159a428a7a1279c22e746db2538" FOREIGN KEY ("working_day_id") REFERENCES "working_days"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_4b8a30a0d3e3c77d07ba91d861a" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_421761540aa42ee87d60a8869d9" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_visits" ADD CONSTRAINT "FK_5a4541ff73326a8c271f3783bcc" FOREIGN KEY ("salesman_id") REFERENCES "salesmen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
